services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Answear\WideEyesBundle\Service\ConfigProvider: ~
    Answear\WideEyesBundle\Service\SimilarClient: ~
    Answear\WideEyesBundle\Service\SearchByImageClient: ~
